title: Whisper by JanHoChoi
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'

url: "https://janhochoi.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings add your name
author: JanHoChoi's Whisper
author-name: JanHoChoi
author-pic: profile.jpg
about-author: Game Programmer in Netease®

#修改成你自己的
# Contact links
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

#修改成你自己的社交账号
email: 15917540078@163.com
github: https://github.com/JanHoChoi

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus修改成你自己的
discus_identifier: JanHoCHoi's Whisper
# Add your discus identifier

#intensedebate修改成你自己的
intensedebate_identifier:

# Tracker Google Analytics修改成你自己的
google-analysis:
baidu-analysis:

# Paginate
paginate: 18
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

imagepath: /blogdemo

links:
  - name:         Home
    url:          https://janhochoi.github.io
    external:     false
  - name:         About
    url:          /about
    external:     false

#添加分类步骤：
#1：在_config.yml links1及blog_中添加对应内容
#2：在_includes里面headr.html中添加对应内容
#3：在根目录blog文件中创建对应内容

label1: <span style="font-size:12px">Publish by
label2:  </span>

imagepath: /

links1:
  - name:         所有
    url:          /
    type:         recent
    external:     false
  - name:         Lua
    url:          /blog/lua
    type:         lua
    external:     false
  - name:         Unity Shader相关
    url:          /blog/unity_shader
    type:         unity_shader
    external:     false
  - name:         UGUI
    url:          /blog/ugui
    type:         ugui
    external:     false
  - name:         Wwise相关
    url:          /blog/wwise
    type:         wwise
    external:     false
  - name:         Python
    url:          /blog/python
    type:         python
  - name:         其他
    url:          /blog/others
    type:         others
    external:     false

blog_1:    recent
blog_2:    lua
blog_3:    unity_shader
blog_4:    ugui
blog_5:    wwise
blog_6:    python
blog_99:    others



#permalink: /:year/:month/:day/:title.html
plugins: [jekyll-paginate]