
title: Whisper #Your awesome title
email: 435504339@qq.com
description: > # this means to ignore newlines until "baseurl"
  记录一些日常工作学习的笔记.

baseurl: # the subpath of the site
url: http://janhochoi.github.io/blog # the base hostname & protocol for your site

permalink: janhochoi.github.io
timezone:

favicon: /assets/img/favicon.ico

google_analytics: #UA—XXXXXXXX-X
disqus_shortname: #disqus shortname

user:
  name: JanhoChoi
  pic: /assets/img/profile_icon.jpg
  picAlt: "catbook"
  job: Game Programmer in Netease®
  aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - README.md
  - LICENSE
  - github

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false